name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: sudo apt-get update && sudo apt-get install build-essential python3 python3-pip git
    - name: install meson
      run: python3 -m pip install meson
    - name: install ninja
      run: python3 -m pip install ninja
    - name: project build
      run: meson setup build
    - name: run project test
      run: . run ip_filter test
    - name: run project test
      run: . run ip_filter test
    - name: run project
      run: . run ip_filter
    








